---
jobs:
- name: build-command-side
  public: true
  plan:
  - get: source-code
    trigger: true
  - get: timer
    trigger: true
  - task: package-command-side
    file: source-code/ci/tasks/build-command-side.yml
  - put: push-to-pcf
    params:
      manifest: source-code/command-side/manifest.yml
      path: package-output/pcf-command-side.jar

- name: smoke-test-command-side
  public: true
  plan:
  - get: source-code
    trigger: true
    passed: [build-command-side]
  - get: timer
    trigger: true
    passed: [build-command-side]
  - task: smoke-test-command-side
    file: source-code/ci/tasks/smoke-test-command-side.yml
    params:
      URL: {{cf-cmd-app-url}}
  - put: slack-alert
    params:
      text: |
        The http smoke test for $BUILD_PIPELINE_NAME.$BUILD_JOB_NAME has passed!

resource_types:
- name: slack-notification
  type: docker-image
  source:
    repository: cfcommunity/slack-notification-resource
    tag: latest

resources:
- name: source-code
  type: git
  source:
    uri: https://github.com/benwilcock/pcf-axon-cqrs-demo
    branch: master

- name: timer
  type: time
  source: {interval: 24h}

- name: push-to-pcf
  type: cf
  source:
    api: {{cf-endpoint}}
    username: {{cf-user}}
    password: {{cf-password}}
    organization: {{cf-org}}
    space: {{cf-space}}
    skip_cert_check: true

- name: slack-alert
  type: slack-notification
  source:
    url: {{webhook}}
    insecure: true